# Pre-commit hooks
repos:
  # Execute external scripts
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  # Execute local scripts
  - repo: local
    hooks:
      - id: run-formatter
        name: Run formatter
        entry: poetry poe formatters
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
      - id: run-linter
        name: Run linter
        entry: poetry poe pylint
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
      - id: run-typings
        name: Run typings
        entry: poetry poe typings
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
      - id: run-tests
        name: Run tests
        entry: poetry poe tests
        language: system
        pass_filenames: false
        stages: [pre-push]
