[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Slick Telemetry backend written in python"
authors = ["Slick Telemetry <contact.@slicktelemetry.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.109.0"
fastf1 = "^3.2.0"
uvicorn = { extras = ["standard"], version = "^0.27.0" }

[tool.poetry.group.dev.dependencies]
black = "^24.1.0"
isort = "^5.13.2"
jupyterlab = "^4.0.11"
jupyterlab-code-formatter = "^2.2.1"
pytest = "^7.4.4"
httpx = "^0.26.0"
commitizen = "^3.13.0"
pre-commit = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.commitizen]
version = "0.1.0"
version_files = [
    "app/__init__.py:__version__",
    "pyproject.toml:version",
    "VERSION",
]
update_changelog_on_bump = true
major_version_zero = true
