[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Slick Telemetry backend written in python"
authors = ["Slick Telemetry <devs.@slicktelemetry.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastf1 = "^3.1.6"
fastapi = "^0.106.0"
uvicorn = { extras = ["standard"], version = "^0.24.0.post1" }

[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
jupyterlab = "^4.0.9"
jupyterlab-code-formatter = "^2.2.1"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
