[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Slick Telemetry backend written in python"
authors = ["Pratik Borole <borolepratik@gmail.com>", "Cris Lombardo <bigc4997@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastf1 = "^3.1.6"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0.post1"}

[tool.poetry.group.dev.dependencies]
black = "^23.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
