version: '3.8'

include:
  - supabase-selfhost.yaml
services:
  app:
    container_name: rearwing-dev
    build:
      context: ..
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    env_file:
      - .env
